-- ResourceX: the same tables as schema.sql, for Postgres (Neon on Vercel).
--
-- Applied automatically by backend/app/db.py on the first request after a cold start; every statement is
-- idempotent. Keep it in step with schema.sql (SQLite, used for local development and tests).
-- Money is AUD excluding GST and transport; quantities are metric tonnes.

-- ---------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------

create table if not exists materials (
  key    text primary key,
  label  text not null,
  family text not null check (family in ('ferrous', 'non_ferrous', 'other'))
);

insert into materials (key, label, family) values
  ('steel',     'Steel',                     'ferrous'),
  ('alloys',    'Stainless & other alloys',  'ferrous'),
  ('aluminium', 'Aluminium',                 'non_ferrous'),
  ('copper',    'Copper',                    'non_ferrous'),
  ('brass',     'Brass',                     'non_ferrous'),
  ('plastics',  'Plastics',                  'other'),
  ('paper',     'Paper & card',              'other'),
  ('glass',     'Glass',                     'other'),
  ('ewaste',    'E-scrap',                   'other')
on conflict (key) do nothing;

create table if not exists grades (
  key   text primary key,
  label text not null,
  rank  integer not null unique
);

insert into grades (key, label, rank) values
  ('short_use', 'Short use',      1),
  ('medium',    'Medium quality', 2),
  ('high',      'High quality',   3)
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- Producers (supply)
-- ---------------------------------------------------------------------

create table if not exists producers (
  id                 integer generated by default as identity primary key,

  name               text not null,
  abn                text not null check (abn ~ '^[0-9]{11}$'),
  legal_entity       text,
  activity           text,
  website            text,

  locality           text not null,
  address            text,
  postcode           text check (postcode ~ '^[0-9]{4}$'),
  state              text not null default 'NSW'
                       check (state in ('NSW','VIC','QLD','SA','WA','TAS','ACT','NT')),
  lat                double precision check (lat between -90 and 90),
  lng                double precision check (lng between -180 and 180),
  geo_source         text check (geo_source in ('npi', 'locality', 'user')),

  material_focus     text,
  input_materials    text not null,
  output_material    text not null references materials (key),
  output_quantity_t  double precision not null check (output_quantity_t > 0),
  output_grade       text not null references grades (key),
  compliance         text not null default '[]' check (jsonb_typeof(compliance::jsonb) = 'array'),
  price_aud_per_t    double precision not null check (price_aud_per_t >= 0),
  supply_start       date,
  supply_end         date,

  is_synthetic       boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  check (supply_end is null or supply_start is null or supply_end >= supply_start)
);

create index if not exists producers_material_grade_idx on producers (output_material, output_grade);
create index if not exists producers_abn_idx on producers (abn);

-- ---------------------------------------------------------------------
-- Manufacturers (demand)
-- ---------------------------------------------------------------------

create table if not exists manufacturers (
  id                     integer generated by default as identity primary key,

  name                   text not null,
  abn                    text not null check (abn ~ '^[0-9]{11}$'),
  legal_entity           text,
  activity               text,
  website                text,

  locality               text not null,
  address                text,
  postcode               text check (postcode ~ '^[0-9]{4}$'),
  state                  text not null default 'NSW'
                           check (state in ('NSW','VIC','QLD','SA','WA','TAS','ACT','NT')),
  lat                    double precision check (lat between -90 and 90),
  lng                    double precision check (lng between -180 and 180),
  geo_source             text check (geo_source in ('npi', 'locality', 'user')),

  required_material      text not null references materials (key),
  product                text,
  required_quantity_t    double precision not null check (required_quantity_t > 0),
  budget_aud             double precision not null check (budget_aud >= 0),
  max_price_aud_per_t    double precision
                           generated always as (round((budget_aud / required_quantity_t)::numeric, 2)::double precision) stored,
  output_grade_request   text not null references grades (key),
  order_by               date not null,
  deliver_by             date not null,
  purchase_start         date,
  purchase_end           date,

  is_synthetic           boolean not null default false,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  check (deliver_by >= order_by),
  check (purchase_end is null or purchase_start is null or purchase_end >= purchase_start)
);

create index if not exists manufacturers_material_grade_idx on manufacturers (required_material, output_grade_request);
create index if not exists manufacturers_abn_idx on manufacturers (abn);

-- ---------------------------------------------------------------------
-- Accounts (logins) and sessions
-- ---------------------------------------------------------------------

create table if not exists accounts (
  id                integer generated by default as identity primary key,
  email             text not null unique check (email = lower(email) and email like '%_@_%'),
  password_hash     text not null,  -- 'pbkdf2_sha256$<iterations>$<salt>$<hash>'
  name              text not null,
  company           text not null,
  abn               text not null check (abn ~ '^[0-9]{11}$'),
  role              text not null check (role in ('buyer', 'seller')),
  locality          text not null,
  state             text not null check (state in ('NSW','VIC','QLD','SA','WA','TAS','ACT','NT')),
  lat               double precision not null check (lat between -90 and 90),
  lng               double precision not null check (lng between -180 and 180),
  producer_id       integer references producers (id) on delete set null,
  manufacturer_id   integer references manufacturers (id) on delete set null,
  is_demo           boolean not null default false,
  created_at        timestamptz not null default now()
);

create table if not exists sessions (
  token_hash  text primary key,  -- SHA-256 of the bearer token; the token itself is never stored
  account_id  integer not null references accounts (id) on delete cascade,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null
);

create index if not exists sessions_account_idx on sessions (account_id);

-- ---------------------------------------------------------------------
-- Enquiries (quote requests)
-- ---------------------------------------------------------------------

create table if not exists enquiries (
  id                integer generated by default as identity primary key,
  producer_id       integer references producers (id) on delete cascade,
  manufacturer_id   integer references manufacturers (id) on delete cascade,
  tonnes_per_month  double precision not null check (tonnes_per_month > 0),
  first_delivery    text not null,
  message           text not null default '',
  account_id        integer references accounts (id) on delete set null,
  created_at        timestamptz not null default now(),

  check ((producer_id is null) <> (manufacturer_id is null))
);

-- ---------------------------------------------------------------------
-- Collaborations (several sellers filling one buyer request together)
-- ---------------------------------------------------------------------

create table if not exists collaborations (
  id                     integer generated by default as identity primary key,
  manufacturer_id        integer not null references manufacturers (id) on delete cascade,
  created_by_account_id  integer references accounts (id) on delete set null,
  status                 text not null default 'forming' check (status in ('forming', 'offer_sent', 'withdrawn')),
  message                text not null default '',
  is_synthetic           boolean not null default false,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create table if not exists collaboration_members (
  id                integer generated by default as identity primary key,
  collaboration_id  integer not null references collaborations (id) on delete cascade,
  producer_id       integer references producers (id) on delete set null,
  name              text not null,
  abn               text not null check (abn ~ '^[0-9]{11}$'),
  locality          text not null,
  state             text not null check (state in ('NSW','VIC','QLD','SA','WA','TAS','ACT','NT')),
  tonnes            double precision not null check (tonnes >= 0),
  price_aud_per_t   double precision not null default 0 check (price_aud_per_t >= 0),
  distance_km       double precision not null default 0 check (distance_km >= 0),
  status            text not null check (status in ('lead', 'invited', 'accepted', 'declined')),
  responded_at      timestamptz,
  unique (collaboration_id, abn)
);

create index if not exists collaboration_members_abn_idx on collaboration_members (abn);

-- ---------------------------------------------------------------------
-- Orders (quote requests, offers and joint offers, then their delivery)
-- ---------------------------------------------------------------------

create table if not exists orders (
  id                 integer generated by default as identity primary key,
  producer_id        integer references producers (id) on delete set null,
  manufacturer_id    integer references manufacturers (id) on delete set null,
  buyer_name         text not null,
  buyer_abn          text not null check (buyer_abn ~ '^[0-9]{11}$'),
  buyer_locality     text not null,
  buyer_state        text not null check (buyer_state in ('NSW','VIC','QLD','SA','WA','TAS','ACT','NT')),
  seller_name        text not null,
  seller_abn         text not null check (seller_abn ~ '^[0-9]{11}$'),
  seller_locality    text not null,
  seller_state       text not null check (seller_state in ('NSW','VIC','QLD','SA','WA','TAS','ACT','NT')),
  material           text not null references materials (key),
  grade              text not null,
  tonnes             double precision not null check (tonnes > 0),
  price_aud_per_t    double precision not null check (price_aud_per_t >= 0),
  freight_aud_per_t  double precision not null default 0 check (freight_aud_per_t >= 0),
  distance_km        double precision not null default 0 check (distance_km >= 0),
  status             text not null default 'pending'
                       check (status in ('pending', 'confirmed', 'in_transit', 'delivered', 'cancelled')),
  placed_at          timestamptz not null default now(),
  delivery_date      date not null,
  co2e_avoided_t     double precision not null default 0,
  collaboration_id   integer references collaborations (id) on delete set null,
  partners           text not null default '[]',
  enquiry_id         integer references enquiries (id) on delete set null,
  is_synthetic       boolean not null default false,
  created_at         timestamptz not null default now()
);

create index if not exists orders_buyer_abn_idx on orders (buyer_abn);
create index if not exists orders_seller_abn_idx on orders (seller_abn);

-- ---------------------------------------------------------------------
-- Keep updated_at current
-- ---------------------------------------------------------------------

create or replace function set_updated_at() returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace trigger producers_set_updated_at
  before update on producers
  for each row execute function set_updated_at();

create or replace trigger manufacturers_set_updated_at
  before update on manufacturers
  for each row execute function set_updated_at();

create or replace trigger collaborations_set_updated_at
  before update on collaborations
  for each row execute function set_updated_at();
